[package]
name = "drive"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-multipart = "0.7.2"
actix-web = "4.9.0"
futures = "0.3.31"
mime_guess = "2.0.5"
uuid = { version = "1.15.1", features = ["v4"] }
