version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      ASYNC_PG_DSN: postgresql+asyncpg://postgres:postgres@db/postgres
      PG_DSN: postgresql://postgres:postgres@db/postgres
      REDIS_DSN: redis://redis:6379/0
      CELERY_DSN: redis://redis:6379/1
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      DRIVE_URL: http://drive:8080

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  drive:
    image: shibal_drive
    build:
      context: ../../drive/

  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
